<program> ::= <function>
<function> ::= int <identifier> "(" "void" ")" "{" { <block-item> } "}"
<block-item> ::= <statement> | <declaration>
<declaration> ::= "int" <identifier> ["=" <expr>]  ";"
<statement> ::= return <expr> ";" | <exp> ";" | ";"
<factor> 
    ::= <identifier> 
      | <literal> 
      | <unary-op> <factor> 
      | "(" <expr> ")"
<expr> ::= <factor> | <expr> <binary-op> <expr>
<identifier> ::= ? an identifier ?
<literal> ::= ? a literal value ?
<unary-op> ::= "~" | "-" | "!"
<binary-op> 
    ::= "+" 
      | "-" 
      | "*" 
      | "/"
      | "%" 
      | "<<" 
      | ">>" 
      | "&" 
      | "|" 
      | "^" 
      | "&&" 
      | "||" 
      | "==" 
      | "!=" 
      | ">" 
      | "<" 
      | "<=" 
      | ">="
